language: objective-c
osx_image: xcode7.2
xcode_project: Typesetter.xcodeproj

env:
  matrix:
      - DESTINATION="OS=9.2,name=iPad 2"
      - DESTINATION="OS=9.2,name=iPad Air"
      - DESTINATION="OS=9.2,name=iPad Air 2"
      - DESTINATION="OS=9.2,name=iPad Pro"
      - DESTINATION="OS=9.2,name=iPad Retina"
      - DESTINATION="OS=9.2,name=iPhone 4s"
      - DESTINATION="OS=9.2,name=iPhone 5"
      - DESTINATION="OS=9.2,name=iPhone 5s"
      - DESTINATION="OS=9.2,name=iPhone 6"
      - DESTINATION="OS=9.2,name=iPhone 6s"
      - DESTINATION="OS=9.2,name=iPhone 6 Plus"
      - DESTINATION="OS=9.2,name=iPhone 6s Plus"

before_install:
  - brew update
  - brew install carthage

before_script:
  - carthage update --platform iOS --no-use-binaries

script: ./bin/test

after_success:
    - bash <(curl -s https://codecov.io/bash)

skip_cleanup: true

before_deploy:
    - carthage build --no-skip-current
    - carthage archive Typesetter

notifications:
    email: true

